Use find_packages() in setup.py
Instead of specifying packages manually, use `find_packages()` to
include all the packages to avoid errors like:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmp.72wZqnyZ2i/venv/lib/python3.5/site-packages/brambox/__init__.py", line 14, in <module>
    from . import boxes
ImportError: cannot import name 'boxes'
```

`brambox/boxes` wasn't in the wheel.